#----------------------------------------
# plugins 
#----------------------------------------
[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
hook_source = '''
source ~/AppData/Local/nvim/plugins/ddc.rc.vim
'''
