#----------------------------------------
# plugins 
#----------------------------------------
[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
hook_source = '''
source `=g:rc_dir . 'plugins/ddc.rc.vim'`
'''
