#----------------------------------------
# plugins 
#----------------------------------------
[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
hook_source = '''
source ~/.config/nvim/plugins/ddc.rc.vim
'''

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#on_event = 'InsertEnter'
#hook_source = '''
#source ~/.config/nvim/plugins/deoplete.rc.vim
#'''
#
#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#depends = ['neosnippet-snippets']
#on_event = 'InsertEnter'
#on_f = ['snippets']
